db_file: ~/.config/music-player/music.db
log_file: ~/.config/music-player/player.log
theme: afterglow
log_level: INFO
input_interval: 0.02
debug: true

plugins_paths:
  - ~/.config/music-player/

plugins:
  - test_plug
  - debug
  - bar
  - commands_palette
  - library
  - scan
  - track_scheduler
  - playlist
  - search
  - cloud_s3

local_library: []

cloud: []

playlist:
  columns:
    - field: track_number
      name: NO
      priority: 1
      size: 3
    - field: title
      name: TITLE
      priority: 1
    - field: album
      name: ALBUM
      priority: 1
    - field: artist
      name: ARTIST
      priority: 1
    - field: length
      name: LENGTH
      priority: 1
      size: 6
      format: time
    - field: cloud_synced
      name: C
      priority: 1
      size: 2